# Generated by Django 5.2.8 on 2025-11-20 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_active', models.BooleanField(blank=True, default=True, help_text='Indica se o registro está ativado', verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Indicado quando o registro foi criado', null=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Indicado quando o registro foi alterado', null=True, verbose_name='Data de alteração')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='Nome')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Sobrenome')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('manager', 'Gerente'), ('user', 'Usuário')], default='user', max_length=20, verbose_name='Role')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Superuser')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Data de cadastro')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_token_jti', models.CharField(help_text='Identificador único do refresh token (JTI)', max_length=255, unique=True, verbose_name='Token JTI')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Endereço IP de onde foi feito o login', null=True, verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, help_text='Informações do navegador/dispositivo', verbose_name='User Agent')),
                ('device_name', models.CharField(blank=True, help_text='Nome amigável do dispositivo (ex: Chrome no Windows)', max_length=255, verbose_name='Nome do Dispositivo')),
                ('location', models.CharField(blank=True, help_text='Localização aproximada (cidade, país)', max_length=255, verbose_name='Localização')),
                ('is_current', models.BooleanField(default=False, help_text='Indica se é a sessão atual do usuário', verbose_name='Sessão Atual')),
                ('last_activity', models.DateTimeField(auto_now=True, help_text='Última vez que esta sessão foi usada', verbose_name='Última Atividade')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Quando o login foi realizado', verbose_name='Data de Criação')),
                ('expires_at', models.DateTimeField(help_text='Quando o refresh token expira', verbose_name='Data de Expiração')),
                ('is_revoked', models.BooleanField(default=False, help_text='Se a sessão foi revogada/logout', verbose_name='Revogado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Sessão de Usuário',
                'verbose_name_plural': 'Sessões de Usuários',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_revoked'], name='core_userse_user_id_bb22b0_idx'), models.Index(fields=['refresh_token_jti'], name='core_userse_refresh_bc0746_idx'), models.Index(fields=['is_current'], name='core_userse_is_curr_61d7dc_idx')],
            },
        ),
    ]
