# Generated by Django 5.2.8 on 2025-11-21 01:36

from django.db import migrations
from django.contrib.auth.hashers import make_password



def forwards(apps, schema_editor):
    User = apps.get_model("core", "User")
    users = [
        {
            "email": "user@example.com",
            "username": "user",
            "first_name": "User",
            "last_name": "Test",
            "password": "user123",
            "is_superuser": False,
            "is_staff": False,
            "role": "user",
            "phone": "14998545414"
        },
        {
            "email": "manager@example.com",
            "username": "manager",
            "first_name": "Manager",
            "last_name": "Test",
            "password": "manager123",
            "is_superuser": False,
            "is_staff": True,
            "role": "manager",
            "phone": "18997885425"
        }
    ]
    for user in users:
        password = user.pop('password')
        user['password'] = make_password(password)
        User.objects.create(**user)


def backwards(apps, schema_editor):
    User = apps.get_model("core", "User")
    User.objects.filter(role__in=["user", "manager"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_create_models'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
