# Generated by Django 5.2.8 on 2025-11-18 21:48
from django.contrib.postgres.operations import BtreeGistExtension

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        BtreeGistExtension(),
    ]
