# Generated by Django 5.2.8 on 2025-11-18 20:48

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(blank=True, default=True, help_text='Indica se o registro está ativado', verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Indicado quando o registro foi criado', null=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Indicado quando o registro foi alterado', null=True, verbose_name='Data de alteração')),
                ('description', models.CharField(help_text='Descrição da localização: Ex: Predio A localizado próximoa a Rua Y', max_length=512, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Localização',
                'verbose_name_plural': 'Localizações',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(blank=True, default=True, help_text='Indica se o registro está ativado', verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Indicado quando o registro foi criado', null=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Indicado quando o registro foi alterado', null=True, verbose_name='Data de alteração')),
                ('description', models.CharField(help_text='Descrição do objeto', max_length=512, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(blank=True, default=True, help_text='Indica se o registro está ativado', verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Indicado quando o registro foi criado', null=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Indicado quando o registro foi alterado', null=True, verbose_name='Data de alteração')),
                ('capacity', models.PositiveIntegerField(help_text='Capacidade de pessoas na sala, ex: 10', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacidade')),
                ('location', models.ForeignKey(help_text='Chave estrangeira da tabela Location', on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='booking.location')),
                ('resources', models.ManyToManyField(blank=True, related_name='rooms', to='booking.resource')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(blank=True, default=True, help_text='Indica se o registro está ativado', verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Indicado quando o registro foi criado', null=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Indicado quando o registro foi alterado', null=True, verbose_name='Data de alteração')),
                ('date_booking', models.DateField(help_text='Data da reserva', verbose_name='Data do reserva')),
                ('start_time_booking', models.TimeField(help_text='Hora inicial da reserva', verbose_name='Inicio da reserva')),
                ('end_time_booking', models.TimeField(help_text='Hora final da reserva', verbose_name='Fim da reserva')),
                ('has_coffee_break', models.BooleanField(default=False, help_text='Indica se na reunião irá precisar de parada para coffe break', verbose_name='Terá para lanche + café?')),
                ('coffee_break_headcount', models.PositiveIntegerField(default=1, help_text='Quantidade de pessoas para coffe break', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade de pessoas para coffe break')),
                ('manager', models.ForeignKey(help_text='Chave estrangeira da tabela User', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(help_text='Chave estrangeira da tabela Room', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.room')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['date_booking', 'start_time_booking', 'room'],
            },
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('name', 'location'), name='unique_room_name_per_location'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['room', 'date_booking'], name='booking_boo_room_id_9580d6_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('room', '='), ('date_booking', '='), (models.Func(models.F('start_time_booking'), models.F('end_time_booking'), function='timerange', output_field=django.contrib.postgres.fields.ranges.DateTimeRangeField()), '&&')], name='withtout_overlaps_booking'),
        ),
    ]
