# Generated by Django 5.2.8 on 2025-11-20 17:46

import booking.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_add_btree_gist_extension'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(blank=True, default=True, help_text='Indica se o registro está ativado', verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Indicado quando o registro foi criado', null=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Indicado quando o registro foi alterado', null=True, verbose_name='Data de alteração')),
                ('name', models.CharField(help_text='Nome da localizaçao, ex: Prédio A', max_length=100, unique=True, verbose_name='Nome')),
                ('address', models.CharField(help_text='Endereço da localização, ex: Rua XYZ', max_length=100)),
                ('city', models.CharField(help_text='Cidade', max_length=100)),
                ('state', models.CharField(help_text='Estado (sigla com 2 letras, ex: SP)', max_length=2, validators=[booking.validators.validate_brazilian_state])),
                ('cep', models.CharField(help_text='CEP no formato: XXXXX-XXX', max_length=9, validators=[django.core.validators.RegexValidator(code='invalid_cep', message='CEP deve estar no formato: XXXXX-XXX (ex: 17607-140)', regex='^\\d{5}-\\d{3}$')])),
                ('description', models.CharField(help_text='Descrição da localização: Ex: Predio A localizado próximoa a Rua Y', max_length=512, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Localização',
                'verbose_name_plural': 'Localizações',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(blank=True, default=True, help_text='Indica se o registro está ativado', verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Indicado quando o registro foi criado', null=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Indicado quando o registro foi alterado', null=True, verbose_name='Data de alteração')),
                ('name', models.CharField(help_text='Nome do objeto', max_length=100, unique=True, verbose_name='Nome')),
                ('description', models.CharField(help_text='Descrição do objeto', max_length=512, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(blank=True, default=True, help_text='Indica se o registro está ativado', verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Indicado quando o registro foi criado', null=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Indicado quando o registro foi alterado', null=True, verbose_name='Data de alteração')),
                ('name', models.CharField(help_text='Nome da sala, ex: Sala 101', max_length=100, verbose_name='Nome')),
                ('capacity', models.PositiveIntegerField(help_text='Capacidade de pessoas na sala, ex: 10', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacidade')),
                ('location', models.ForeignKey(help_text='Chave estrangeira da tabela Location', on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='booking.location')),
                ('resources', models.ManyToManyField(blank=True, related_name='rooms', to='booking.resource')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(blank=True, default=True, help_text='Indica se o registro está ativado', verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Indicado quando o registro foi criado', null=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Indicado quando o registro foi alterado', null=True, verbose_name='Data de alteração')),
                ('date_booking', models.DateField(help_text='Data da reserva', verbose_name='Data do reserva')),
                ('start_datetime', models.DateTimeField(help_text='Hora inicial da reserva', verbose_name='Inicio da reserva')),
                ('end_datetime', models.DateTimeField(help_text='Hora final da reserva', verbose_name='Fim da reserva')),
                ('has_coffee_break', models.BooleanField(default=False, help_text='Indica se na reunião irá precisar de parada para coffe break', verbose_name='Terá para lanche + café?')),
                ('coffee_break_headcount', models.PositiveIntegerField(default=1, help_text='Quantidade de pessoas para coffe break', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade de pessoas para coffe break')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmada'), ('cancelled', 'Cancelada'), ('completed', 'Concluída')], default='pending', help_text='Status da reserva', max_length=20, verbose_name='Status')),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='Quando a reserva foi confirmada', null=True, verbose_name='Data/Hora de confirmação')),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='Quando a reserva foi cancelada', null=True, verbose_name='Data/Hora de cancelamento')),
                ('cancellation_reason', models.TextField(blank=True, help_text='Motivo pelo qual a reserva foi cancelada', null=True, verbose_name='Motivo do cancelamento')),
                ('notes', models.TextField(blank=True, help_text='Observações gerais sobre a reserva', null=True, verbose_name='Observações')),
                ('cancelled_by', models.ForeignKey(blank=True, help_text='Usuário que cancelou a reserva', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_bookings', to=settings.AUTH_USER_MODEL)),
                ('confirmed_by', models.ForeignKey(blank=True, help_text='Usuário que confirmou a reserva', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_bookings', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(help_text='Chave estrangeira da tabela User', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(help_text='Chave estrangeira da tabela Room', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.room')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['date_booking', 'start_datetime', 'room'],
            },
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('name', 'location'), name='unique_room_name_per_location'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['room', 'date_booking'], name='booking_boo_room_id_9580d6_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'date_booking'], name='booking_boo_status_9a6bf6_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['manager', 'status'], name='booking_boo_manager_c339ea_idx'),
        ),
    ]
