# Generated by Django 5.2.8 on 2025-11-21 01:20

from django.db import migrations



def forwards(apps, schema_editor):
    Location = apps.get_model("booking", "Location")
    Resource = apps.get_model("booking", "Resource")
    Room = apps.get_model("booking", "Room")

    locations = [
        {
            "name": "Coworking Google",
            "address": "Rua X",
            'city': 'São Paulo',
            'state': 'SP',
            'cep': '01000-000',
            "description": "Coworking Google"
        },
        {
            "name": "Expo São Paulo",
            "address": "Rua Y",
            'city': 'São Paulo',
            'state': 'SP',
            'cep': '02000-000',
            "description": "Expo São Paulo"
        },
        {
            "name": "Prédio Alphaville ",
            "address": "Rua Z",
            'city': 'São Paulo',
            'state': 'SP',
            'cep': '03000-000',
            "description": "Prédio Alphaville"
        },
    ]
    for location in locations:
        Location.objects.create(**location)

    #  "location": Location.objects.get(name="Coworking Google")
    resources = [
        {"name": "TV", "description": "Televisão da sala  de reunião"},
        {"name": "Quadro Branco", "description": "Quadro branco da sala  de reunião"},
        {"name": "Projetor", "description": "Projetor da sala  de reunião"},
        {"name": "Notebook", "description": "Notebook da sala  de reunião"},
    ]
    for resource in resources:
        Resource.objects.create(**resource)

    resources = Resource.objects.all()
    rooms = [
        {
            "name": "Sala de Reunião 1",
            "location": Location.objects.get(name="Coworking Google"),
            "capacity": 10,
            "resources": [resources.get(name="TV"), resources.get(name="Quadro Branco")]
        },
        {
            "name": "Sala de Reunião 2",
            "location": Location.objects.get(name="Expo São Paulo"),
            "capacity": 20,
            "resources": [resources.get(name="Projetor"), resources.get(name="Notebook")]
        },
        {
            "name": "Auditório",
            "location": Location.objects.get(name="Prédio Alphaville "),
            "capacity": 100,
            "resources": [resources.get(name="Projetor"), resources.get(name="TV")]
        },
    ]
    for room in rooms:
        name = room.pop("name")
        location = room.pop("location")
        capacity = room.pop("capacity")
        resources = room.pop("resources")
        room = Room.objects.create(name=name, location=location, capacity=capacity)
        room.resources.set(resources)


def backwards(apps, schema_editor):
    Location = apps.get_model("booking", "Location")
    Location.objects.all().delete()

    Resource = apps.get_model("booking", "Resource")
    Resource.objects.all().delete()

    Room = apps.get_model("booking", "Room")
    Room.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_create_models'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
